---
- name: Add unit file for Frontend
  template:
    src: docker.frontend.service.j2
    dest: /etc/systemd/system/docker.frontend.service
#  notify: reload docker.frontend

- name: Start docker.frontend.service
  systemd:
    state: started
    name: docker.frontend
    daemon_reload: yes

- name: Enable docker.frontend.service
  systemd:
    name: docker.frontend
    enabled: yes
