---
# tasks file for docker-ce
- name: Install DNF plugins core
  dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: true

- name: test repo
  dnf:
    enablerepo: docker-ce
    state: present

- name: Install docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
